name: "[DEVELOP] - Build & Deploy"

on:
  push:
    branches:
      - develop

env:
  DOCKER_APP_REPOSITORY_NAME: alvarobgs/customermanagement
  GITHUB_INFRA_REPOSITORY_NAME: easy-ticket/infra-helm-deployment-charts
  PROJECT_NAME: customermanagement

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # clona o projeto no repositório
      - uses: actions/checkout@v3

      # seta a jdk 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package -DskipTests -f app/pom.xml

      # faz o cache das dependências baixadas
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
           path: ~/.m2
           key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
           restore-keys: ${{ runner.os }}-m2

      # executa os testes unitários
      - name: Maven Test
        run: mvn test -f app/pom.xml

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      # publica no dockerhub
      - name: Publish to Docker Hub v4
        uses: docker/build-push-action@v4
        with:
          push: true
          context: ./app
          tags: ${{ env.DOCKER_APP_REPOSITORY_NAME }}:${{ github.sha }}

      - name: Checkout chart repo
        uses: actions/checkout@v3
        with:
          repository: ${{ env.GITHUB_INFRA_REPOSITORY_NAME }}
          ref: main
          token: ${{ secrets.CHECKOUT_ACTION_TOKEN }}
          path: infra

      - name: Update project chart to latest tag
        uses: mikefarah/yq@master
        with:
          cmd: yq -i '.image.tag = "${{ github.sha }}"' infra/app/${{ env.PROJECT_NAME }}/values.yaml -v

      - name: Move infra repo outside
        run: |
          mv infra ../infra

      - name: Commit chart update
        run: |
            cd ../infra
            git config user.name github-actions
            git config user.email github-actions@github.com
            git add .
            git commit -m "Update image tag for project ${{ env.PROJECT_NAME }} to value ${{ github.sha }}"
            git push